scriptencoding utf-8

filetype plugin on

let mapleader = ","
nnoremap <leader><space> :nohlsearch<cr>
nnoremap <leader>l :set list!<cr>
nnoremap <leader>n :set relativenumber!<cr>

nnoremap j gj
nnoremap k gk
" For cycling through buffers
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Don't use Ex mode, use Q for formatting
map Q gq

" If I forgot to use sudo
cmap w!! w !sudo tee > /dev/null %

set autochdir           " Might cause plugin problems
set autoindent          " Auto indenting
set autoread            " Read the file when it's changed from the outside
set backspace=2         " Allow backspacing over everything
set backup
set backupdir=~/.vim/backup
set directory=~/.vim/tmp
set history=100
set hlsearch            " Highlight search
set ignorecase          " Ignore case when searching
set incsearch           " Incremental
set listchars=eol:¬,tab:>·,trail:~,extends:>,precedes:<,space:␣
set mouse=a             " Enable for all modes
set number              " Line numbering
set numberwidth=3       " Do not use an annoyingly wide number line column
set ruler               " Show cursor position
set scrolloff=7         " Always keep some context visible
set shell=sh            " Problems when using Fish
set shiftwidth=4
set showcmd             " Display incomplete commands
set showmatch           " Show matching brackets
set smartcase
set suffixes+=.info,.aux,.log,.dvi,.bbl,.out,.o,.lo,.pdf
set tabstop=4
set viminfo='20,<500,%,n~/.vim/viminfo   " Keep a .viminfo file.
let g:miniBufExplMapWindowNavArrows = 1
let g:miniBufExplMapCTabSwitchBufs = 1
let g:miniBufExplUseSingleClick = 1

" Autosave when the buffer loses focus
autocmd BufLeave,FocusLost * silent! wa

" vim: set fenc=utf-8 tw=80 sw=2 sts=2 et :
